/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiWheelRouteImport } from './routes/ui/wheel'
import { Route as UiSwitchRouteImport } from './routes/ui/switch'
import { Route as UiSpinnerRouteImport } from './routes/ui/spinner'
import { Route as UiSignaturePadRouteImport } from './routes/ui/signature-pad'
import { Route as UiRowRouteImport } from './routes/ui/row'
import { Route as UiPillRadioRouteImport } from './routes/ui/pill-radio'
import { Route as UiPanelRouteImport } from './routes/ui/panel'
import { Route as UiPaletteRouteImport } from './routes/ui/palette'
import { Route as UiMultiselectRouteImport } from './routes/ui/multiselect'
import { Route as UiMemoRouteImport } from './routes/ui/memo'
import { Route as UiListRouteImport } from './routes/ui/list'
import { Route as UiInputRouteImport } from './routes/ui/input'
import { Route as UiHyperlinkRouteImport } from './routes/ui/hyperlink'
import { Route as UiFieldRouteImport } from './routes/ui/field'
import { Route as UiExpandableRouteImport } from './routes/ui/expandable'
import { Route as UiDialogRouteImport } from './routes/ui/dialog'
import { Route as UiColorPickerRouteImport } from './routes/ui/color-picker'
import { Route as UiCodeBlockRouteImport } from './routes/ui/code-block'
import { Route as UiCapsuleButtonRouteImport } from './routes/ui/capsule-button'
import { Route as UiCalendarRouteImport } from './routes/ui/calendar'
import { Route as UiButtonRouteImport } from './routes/ui/button'
import { Route as UiBadgeRouteImport } from './routes/ui/badge'
import { Route as UiAutocompleteRouteImport } from './routes/ui/autocomplete'
import { Route as ComboTimeWheelPickerRouteImport } from './routes/combo/time-wheel-picker'
import { Route as ComboSignatureDialogRouteImport } from './routes/combo/signature-dialog'
import { Route as ComboMonthYearPickerRouteImport } from './routes/combo/month-year-picker'
import { Route as ComboIconButtonRouteImport } from './routes/combo/icon-button'
import { Route as ComboFormFieldRouteImport } from './routes/combo/form-field'
import { Route as ComboDataTableRouteImport } from './routes/combo/data-table'
import { Route as ComboConfirmationRouteImport } from './routes/combo/confirmation'
import { Route as AnimationAnimation1RouteImport } from './routes/animation/animation1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiWheelRoute = UiWheelRouteImport.update({
  id: '/ui/wheel',
  path: '/ui/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const UiSwitchRoute = UiSwitchRouteImport.update({
  id: '/ui/switch',
  path: '/ui/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const UiSpinnerRoute = UiSpinnerRouteImport.update({
  id: '/ui/spinner',
  path: '/ui/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const UiSignaturePadRoute = UiSignaturePadRouteImport.update({
  id: '/ui/signature-pad',
  path: '/ui/signature-pad',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRowRoute = UiRowRouteImport.update({
  id: '/ui/row',
  path: '/ui/row',
  getParentRoute: () => rootRouteImport,
} as any)
const UiPillRadioRoute = UiPillRadioRouteImport.update({
  id: '/ui/pill-radio',
  path: '/ui/pill-radio',
  getParentRoute: () => rootRouteImport,
} as any)
const UiPanelRoute = UiPanelRouteImport.update({
  id: '/ui/panel',
  path: '/ui/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const UiPaletteRoute = UiPaletteRouteImport.update({
  id: '/ui/palette',
  path: '/ui/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const UiMultiselectRoute = UiMultiselectRouteImport.update({
  id: '/ui/multiselect',
  path: '/ui/multiselect',
  getParentRoute: () => rootRouteImport,
} as any)
const UiMemoRoute = UiMemoRouteImport.update({
  id: '/ui/memo',
  path: '/ui/memo',
  getParentRoute: () => rootRouteImport,
} as any)
const UiListRoute = UiListRouteImport.update({
  id: '/ui/list',
  path: '/ui/list',
  getParentRoute: () => rootRouteImport,
} as any)
const UiInputRoute = UiInputRouteImport.update({
  id: '/ui/input',
  path: '/ui/input',
  getParentRoute: () => rootRouteImport,
} as any)
const UiHyperlinkRoute = UiHyperlinkRouteImport.update({
  id: '/ui/hyperlink',
  path: '/ui/hyperlink',
  getParentRoute: () => rootRouteImport,
} as any)
const UiFieldRoute = UiFieldRouteImport.update({
  id: '/ui/field',
  path: '/ui/field',
  getParentRoute: () => rootRouteImport,
} as any)
const UiExpandableRoute = UiExpandableRouteImport.update({
  id: '/ui/expandable',
  path: '/ui/expandable',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDialogRoute = UiDialogRouteImport.update({
  id: '/ui/dialog',
  path: '/ui/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const UiColorPickerRoute = UiColorPickerRouteImport.update({
  id: '/ui/color-picker',
  path: '/ui/color-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const UiCodeBlockRoute = UiCodeBlockRouteImport.update({
  id: '/ui/code-block',
  path: '/ui/code-block',
  getParentRoute: () => rootRouteImport,
} as any)
const UiCapsuleButtonRoute = UiCapsuleButtonRouteImport.update({
  id: '/ui/capsule-button',
  path: '/ui/capsule-button',
  getParentRoute: () => rootRouteImport,
} as any)
const UiCalendarRoute = UiCalendarRouteImport.update({
  id: '/ui/calendar',
  path: '/ui/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const UiButtonRoute = UiButtonRouteImport.update({
  id: '/ui/button',
  path: '/ui/button',
  getParentRoute: () => rootRouteImport,
} as any)
const UiBadgeRoute = UiBadgeRouteImport.update({
  id: '/ui/badge',
  path: '/ui/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const UiAutocompleteRoute = UiAutocompleteRouteImport.update({
  id: '/ui/autocomplete',
  path: '/ui/autocomplete',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboTimeWheelPickerRoute = ComboTimeWheelPickerRouteImport.update({
  id: '/combo/time-wheel-picker',
  path: '/combo/time-wheel-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboSignatureDialogRoute = ComboSignatureDialogRouteImport.update({
  id: '/combo/signature-dialog',
  path: '/combo/signature-dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboMonthYearPickerRoute = ComboMonthYearPickerRouteImport.update({
  id: '/combo/month-year-picker',
  path: '/combo/month-year-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboIconButtonRoute = ComboIconButtonRouteImport.update({
  id: '/combo/icon-button',
  path: '/combo/icon-button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboFormFieldRoute = ComboFormFieldRouteImport.update({
  id: '/combo/form-field',
  path: '/combo/form-field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboDataTableRoute = ComboDataTableRouteImport.update({
  id: '/combo/data-table',
  path: '/combo/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboConfirmationRoute = ComboConfirmationRouteImport.update({
  id: '/combo/confirmation',
  path: '/combo/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationAnimation1Route = AnimationAnimation1RouteImport.update({
  id: '/animation/animation1',
  path: '/animation/animation1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animation/animation1': typeof AnimationAnimation1Route
  '/combo/confirmation': typeof ComboConfirmationRoute
  '/combo/data-table': typeof ComboDataTableRoute
  '/combo/form-field': typeof ComboFormFieldRoute
  '/combo/icon-button': typeof ComboIconButtonRoute
  '/combo/month-year-picker': typeof ComboMonthYearPickerRoute
  '/combo/signature-dialog': typeof ComboSignatureDialogRoute
  '/combo/time-wheel-picker': typeof ComboTimeWheelPickerRoute
  '/ui/autocomplete': typeof UiAutocompleteRoute
  '/ui/badge': typeof UiBadgeRoute
  '/ui/button': typeof UiButtonRoute
  '/ui/calendar': typeof UiCalendarRoute
  '/ui/capsule-button': typeof UiCapsuleButtonRoute
  '/ui/code-block': typeof UiCodeBlockRoute
  '/ui/color-picker': typeof UiColorPickerRoute
  '/ui/dialog': typeof UiDialogRoute
  '/ui/expandable': typeof UiExpandableRoute
  '/ui/field': typeof UiFieldRoute
  '/ui/hyperlink': typeof UiHyperlinkRoute
  '/ui/input': typeof UiInputRoute
  '/ui/list': typeof UiListRoute
  '/ui/memo': typeof UiMemoRoute
  '/ui/multiselect': typeof UiMultiselectRoute
  '/ui/palette': typeof UiPaletteRoute
  '/ui/panel': typeof UiPanelRoute
  '/ui/pill-radio': typeof UiPillRadioRoute
  '/ui/row': typeof UiRowRoute
  '/ui/signature-pad': typeof UiSignaturePadRoute
  '/ui/spinner': typeof UiSpinnerRoute
  '/ui/switch': typeof UiSwitchRoute
  '/ui/wheel': typeof UiWheelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animation/animation1': typeof AnimationAnimation1Route
  '/combo/confirmation': typeof ComboConfirmationRoute
  '/combo/data-table': typeof ComboDataTableRoute
  '/combo/form-field': typeof ComboFormFieldRoute
  '/combo/icon-button': typeof ComboIconButtonRoute
  '/combo/month-year-picker': typeof ComboMonthYearPickerRoute
  '/combo/signature-dialog': typeof ComboSignatureDialogRoute
  '/combo/time-wheel-picker': typeof ComboTimeWheelPickerRoute
  '/ui/autocomplete': typeof UiAutocompleteRoute
  '/ui/badge': typeof UiBadgeRoute
  '/ui/button': typeof UiButtonRoute
  '/ui/calendar': typeof UiCalendarRoute
  '/ui/capsule-button': typeof UiCapsuleButtonRoute
  '/ui/code-block': typeof UiCodeBlockRoute
  '/ui/color-picker': typeof UiColorPickerRoute
  '/ui/dialog': typeof UiDialogRoute
  '/ui/expandable': typeof UiExpandableRoute
  '/ui/field': typeof UiFieldRoute
  '/ui/hyperlink': typeof UiHyperlinkRoute
  '/ui/input': typeof UiInputRoute
  '/ui/list': typeof UiListRoute
  '/ui/memo': typeof UiMemoRoute
  '/ui/multiselect': typeof UiMultiselectRoute
  '/ui/palette': typeof UiPaletteRoute
  '/ui/panel': typeof UiPanelRoute
  '/ui/pill-radio': typeof UiPillRadioRoute
  '/ui/row': typeof UiRowRoute
  '/ui/signature-pad': typeof UiSignaturePadRoute
  '/ui/spinner': typeof UiSpinnerRoute
  '/ui/switch': typeof UiSwitchRoute
  '/ui/wheel': typeof UiWheelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animation/animation1': typeof AnimationAnimation1Route
  '/combo/confirmation': typeof ComboConfirmationRoute
  '/combo/data-table': typeof ComboDataTableRoute
  '/combo/form-field': typeof ComboFormFieldRoute
  '/combo/icon-button': typeof ComboIconButtonRoute
  '/combo/month-year-picker': typeof ComboMonthYearPickerRoute
  '/combo/signature-dialog': typeof ComboSignatureDialogRoute
  '/combo/time-wheel-picker': typeof ComboTimeWheelPickerRoute
  '/ui/autocomplete': typeof UiAutocompleteRoute
  '/ui/badge': typeof UiBadgeRoute
  '/ui/button': typeof UiButtonRoute
  '/ui/calendar': typeof UiCalendarRoute
  '/ui/capsule-button': typeof UiCapsuleButtonRoute
  '/ui/code-block': typeof UiCodeBlockRoute
  '/ui/color-picker': typeof UiColorPickerRoute
  '/ui/dialog': typeof UiDialogRoute
  '/ui/expandable': typeof UiExpandableRoute
  '/ui/field': typeof UiFieldRoute
  '/ui/hyperlink': typeof UiHyperlinkRoute
  '/ui/input': typeof UiInputRoute
  '/ui/list': typeof UiListRoute
  '/ui/memo': typeof UiMemoRoute
  '/ui/multiselect': typeof UiMultiselectRoute
  '/ui/palette': typeof UiPaletteRoute
  '/ui/panel': typeof UiPanelRoute
  '/ui/pill-radio': typeof UiPillRadioRoute
  '/ui/row': typeof UiRowRoute
  '/ui/signature-pad': typeof UiSignaturePadRoute
  '/ui/spinner': typeof UiSpinnerRoute
  '/ui/switch': typeof UiSwitchRoute
  '/ui/wheel': typeof UiWheelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animation/animation1'
    | '/combo/confirmation'
    | '/combo/data-table'
    | '/combo/form-field'
    | '/combo/icon-button'
    | '/combo/month-year-picker'
    | '/combo/signature-dialog'
    | '/combo/time-wheel-picker'
    | '/ui/autocomplete'
    | '/ui/badge'
    | '/ui/button'
    | '/ui/calendar'
    | '/ui/capsule-button'
    | '/ui/code-block'
    | '/ui/color-picker'
    | '/ui/dialog'
    | '/ui/expandable'
    | '/ui/field'
    | '/ui/hyperlink'
    | '/ui/input'
    | '/ui/list'
    | '/ui/memo'
    | '/ui/multiselect'
    | '/ui/palette'
    | '/ui/panel'
    | '/ui/pill-radio'
    | '/ui/row'
    | '/ui/signature-pad'
    | '/ui/spinner'
    | '/ui/switch'
    | '/ui/wheel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animation/animation1'
    | '/combo/confirmation'
    | '/combo/data-table'
    | '/combo/form-field'
    | '/combo/icon-button'
    | '/combo/month-year-picker'
    | '/combo/signature-dialog'
    | '/combo/time-wheel-picker'
    | '/ui/autocomplete'
    | '/ui/badge'
    | '/ui/button'
    | '/ui/calendar'
    | '/ui/capsule-button'
    | '/ui/code-block'
    | '/ui/color-picker'
    | '/ui/dialog'
    | '/ui/expandable'
    | '/ui/field'
    | '/ui/hyperlink'
    | '/ui/input'
    | '/ui/list'
    | '/ui/memo'
    | '/ui/multiselect'
    | '/ui/palette'
    | '/ui/panel'
    | '/ui/pill-radio'
    | '/ui/row'
    | '/ui/signature-pad'
    | '/ui/spinner'
    | '/ui/switch'
    | '/ui/wheel'
  id:
    | '__root__'
    | '/'
    | '/animation/animation1'
    | '/combo/confirmation'
    | '/combo/data-table'
    | '/combo/form-field'
    | '/combo/icon-button'
    | '/combo/month-year-picker'
    | '/combo/signature-dialog'
    | '/combo/time-wheel-picker'
    | '/ui/autocomplete'
    | '/ui/badge'
    | '/ui/button'
    | '/ui/calendar'
    | '/ui/capsule-button'
    | '/ui/code-block'
    | '/ui/color-picker'
    | '/ui/dialog'
    | '/ui/expandable'
    | '/ui/field'
    | '/ui/hyperlink'
    | '/ui/input'
    | '/ui/list'
    | '/ui/memo'
    | '/ui/multiselect'
    | '/ui/palette'
    | '/ui/panel'
    | '/ui/pill-radio'
    | '/ui/row'
    | '/ui/signature-pad'
    | '/ui/spinner'
    | '/ui/switch'
    | '/ui/wheel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimationAnimation1Route: typeof AnimationAnimation1Route
  ComboConfirmationRoute: typeof ComboConfirmationRoute
  ComboDataTableRoute: typeof ComboDataTableRoute
  ComboFormFieldRoute: typeof ComboFormFieldRoute
  ComboIconButtonRoute: typeof ComboIconButtonRoute
  ComboMonthYearPickerRoute: typeof ComboMonthYearPickerRoute
  ComboSignatureDialogRoute: typeof ComboSignatureDialogRoute
  ComboTimeWheelPickerRoute: typeof ComboTimeWheelPickerRoute
  UiAutocompleteRoute: typeof UiAutocompleteRoute
  UiBadgeRoute: typeof UiBadgeRoute
  UiButtonRoute: typeof UiButtonRoute
  UiCalendarRoute: typeof UiCalendarRoute
  UiCapsuleButtonRoute: typeof UiCapsuleButtonRoute
  UiCodeBlockRoute: typeof UiCodeBlockRoute
  UiColorPickerRoute: typeof UiColorPickerRoute
  UiDialogRoute: typeof UiDialogRoute
  UiExpandableRoute: typeof UiExpandableRoute
  UiFieldRoute: typeof UiFieldRoute
  UiHyperlinkRoute: typeof UiHyperlinkRoute
  UiInputRoute: typeof UiInputRoute
  UiListRoute: typeof UiListRoute
  UiMemoRoute: typeof UiMemoRoute
  UiMultiselectRoute: typeof UiMultiselectRoute
  UiPaletteRoute: typeof UiPaletteRoute
  UiPanelRoute: typeof UiPanelRoute
  UiPillRadioRoute: typeof UiPillRadioRoute
  UiRowRoute: typeof UiRowRoute
  UiSignaturePadRoute: typeof UiSignaturePadRoute
  UiSpinnerRoute: typeof UiSpinnerRoute
  UiSwitchRoute: typeof UiSwitchRoute
  UiWheelRoute: typeof UiWheelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/wheel': {
      id: '/ui/wheel'
      path: '/ui/wheel'
      fullPath: '/ui/wheel'
      preLoaderRoute: typeof UiWheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/switch': {
      id: '/ui/switch'
      path: '/ui/switch'
      fullPath: '/ui/switch'
      preLoaderRoute: typeof UiSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/spinner': {
      id: '/ui/spinner'
      path: '/ui/spinner'
      fullPath: '/ui/spinner'
      preLoaderRoute: typeof UiSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/signature-pad': {
      id: '/ui/signature-pad'
      path: '/ui/signature-pad'
      fullPath: '/ui/signature-pad'
      preLoaderRoute: typeof UiSignaturePadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/row': {
      id: '/ui/row'
      path: '/ui/row'
      fullPath: '/ui/row'
      preLoaderRoute: typeof UiRowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/pill-radio': {
      id: '/ui/pill-radio'
      path: '/ui/pill-radio'
      fullPath: '/ui/pill-radio'
      preLoaderRoute: typeof UiPillRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/panel': {
      id: '/ui/panel'
      path: '/ui/panel'
      fullPath: '/ui/panel'
      preLoaderRoute: typeof UiPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/palette': {
      id: '/ui/palette'
      path: '/ui/palette'
      fullPath: '/ui/palette'
      preLoaderRoute: typeof UiPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/multiselect': {
      id: '/ui/multiselect'
      path: '/ui/multiselect'
      fullPath: '/ui/multiselect'
      preLoaderRoute: typeof UiMultiselectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/memo': {
      id: '/ui/memo'
      path: '/ui/memo'
      fullPath: '/ui/memo'
      preLoaderRoute: typeof UiMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/list': {
      id: '/ui/list'
      path: '/ui/list'
      fullPath: '/ui/list'
      preLoaderRoute: typeof UiListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/input': {
      id: '/ui/input'
      path: '/ui/input'
      fullPath: '/ui/input'
      preLoaderRoute: typeof UiInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/hyperlink': {
      id: '/ui/hyperlink'
      path: '/ui/hyperlink'
      fullPath: '/ui/hyperlink'
      preLoaderRoute: typeof UiHyperlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/field': {
      id: '/ui/field'
      path: '/ui/field'
      fullPath: '/ui/field'
      preLoaderRoute: typeof UiFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/expandable': {
      id: '/ui/expandable'
      path: '/ui/expandable'
      fullPath: '/ui/expandable'
      preLoaderRoute: typeof UiExpandableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/dialog': {
      id: '/ui/dialog'
      path: '/ui/dialog'
      fullPath: '/ui/dialog'
      preLoaderRoute: typeof UiDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/color-picker': {
      id: '/ui/color-picker'
      path: '/ui/color-picker'
      fullPath: '/ui/color-picker'
      preLoaderRoute: typeof UiColorPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/code-block': {
      id: '/ui/code-block'
      path: '/ui/code-block'
      fullPath: '/ui/code-block'
      preLoaderRoute: typeof UiCodeBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/capsule-button': {
      id: '/ui/capsule-button'
      path: '/ui/capsule-button'
      fullPath: '/ui/capsule-button'
      preLoaderRoute: typeof UiCapsuleButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/calendar': {
      id: '/ui/calendar'
      path: '/ui/calendar'
      fullPath: '/ui/calendar'
      preLoaderRoute: typeof UiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/button': {
      id: '/ui/button'
      path: '/ui/button'
      fullPath: '/ui/button'
      preLoaderRoute: typeof UiButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/badge': {
      id: '/ui/badge'
      path: '/ui/badge'
      fullPath: '/ui/badge'
      preLoaderRoute: typeof UiBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/autocomplete': {
      id: '/ui/autocomplete'
      path: '/ui/autocomplete'
      fullPath: '/ui/autocomplete'
      preLoaderRoute: typeof UiAutocompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/time-wheel-picker': {
      id: '/combo/time-wheel-picker'
      path: '/combo/time-wheel-picker'
      fullPath: '/combo/time-wheel-picker'
      preLoaderRoute: typeof ComboTimeWheelPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/signature-dialog': {
      id: '/combo/signature-dialog'
      path: '/combo/signature-dialog'
      fullPath: '/combo/signature-dialog'
      preLoaderRoute: typeof ComboSignatureDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/month-year-picker': {
      id: '/combo/month-year-picker'
      path: '/combo/month-year-picker'
      fullPath: '/combo/month-year-picker'
      preLoaderRoute: typeof ComboMonthYearPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/icon-button': {
      id: '/combo/icon-button'
      path: '/combo/icon-button'
      fullPath: '/combo/icon-button'
      preLoaderRoute: typeof ComboIconButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/form-field': {
      id: '/combo/form-field'
      path: '/combo/form-field'
      fullPath: '/combo/form-field'
      preLoaderRoute: typeof ComboFormFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/data-table': {
      id: '/combo/data-table'
      path: '/combo/data-table'
      fullPath: '/combo/data-table'
      preLoaderRoute: typeof ComboDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/confirmation': {
      id: '/combo/confirmation'
      path: '/combo/confirmation'
      fullPath: '/combo/confirmation'
      preLoaderRoute: typeof ComboConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animation/animation1': {
      id: '/animation/animation1'
      path: '/animation/animation1'
      fullPath: '/animation/animation1'
      preLoaderRoute: typeof AnimationAnimation1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimationAnimation1Route: AnimationAnimation1Route,
  ComboConfirmationRoute: ComboConfirmationRoute,
  ComboDataTableRoute: ComboDataTableRoute,
  ComboFormFieldRoute: ComboFormFieldRoute,
  ComboIconButtonRoute: ComboIconButtonRoute,
  ComboMonthYearPickerRoute: ComboMonthYearPickerRoute,
  ComboSignatureDialogRoute: ComboSignatureDialogRoute,
  ComboTimeWheelPickerRoute: ComboTimeWheelPickerRoute,
  UiAutocompleteRoute: UiAutocompleteRoute,
  UiBadgeRoute: UiBadgeRoute,
  UiButtonRoute: UiButtonRoute,
  UiCalendarRoute: UiCalendarRoute,
  UiCapsuleButtonRoute: UiCapsuleButtonRoute,
  UiCodeBlockRoute: UiCodeBlockRoute,
  UiColorPickerRoute: UiColorPickerRoute,
  UiDialogRoute: UiDialogRoute,
  UiExpandableRoute: UiExpandableRoute,
  UiFieldRoute: UiFieldRoute,
  UiHyperlinkRoute: UiHyperlinkRoute,
  UiInputRoute: UiInputRoute,
  UiListRoute: UiListRoute,
  UiMemoRoute: UiMemoRoute,
  UiMultiselectRoute: UiMultiselectRoute,
  UiPaletteRoute: UiPaletteRoute,
  UiPanelRoute: UiPanelRoute,
  UiPillRadioRoute: UiPillRadioRoute,
  UiRowRoute: UiRowRoute,
  UiSignaturePadRoute: UiSignaturePadRoute,
  UiSpinnerRoute: UiSpinnerRoute,
  UiSwitchRoute: UiSwitchRoute,
  UiWheelRoute: UiWheelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
